server:
  port: 9007

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-sms
  rabbitmq:
    host: 120.77.145.221

aliyun:
  sms:
    accessKeyId : LTAIqszfnkm2kP32
    accessKeySecret : bDjhHu4V6dQVn7bkHFg4MyniVMyfSW
    templateCode: SMS_163848140
    signName: 蓝桥培训