server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-elasticsearch

  data:
    elasticsearch:
      cluster-nodes: 120.77.145.221:9300