server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true


spring:
  application:
    name: project-comment
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.145.221:3306/project_CSDN?characterEncoding=utf-8
    username: root
    password: 0
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 120.77.145.221
    port: 6379